#!/usr/bin/env python3
"""
WiFi CNC Controller - LinuxCNC Configuration Generator

Generates a complete LinuxCNC config folder for the WiFi CNC controller.
Run:  python3 wifi_cnc_setup.py

Creates:
  wifi_cnc_config/
    wifi_cnc.ini
    wifi_cnc.hal
    postgui.hal
"""

import os
import sys

def ask(prompt, default=""):
    if default:
        result = input(f"{prompt} [{default}]: ").strip()
        return result if result else default
    return input(f"{prompt}: ").strip()

def ask_float(prompt, default):
    val = ask(prompt, str(default))
    return float(val)

def ask_int(prompt, default):
    val = ask(prompt, str(default))
    return int(val)

def main():
    print("=" * 50)
    print("  WiFi CNC Controller - LinuxCNC Setup")
    print("=" * 50)
    print()

    # Basic settings
    machine_name = ask("Machine name", "WiFi-CNC")
    esp_ip = ask("ESP32 IP address", "192.168.4.1")
    num_joints = ask_int("Number of axes (1-6)", 3)
    if num_joints < 1:
        num_joints = 1
    if num_joints > 6:
        num_joints = 6

    units = ask("Units (mm or inch)", "mm")
    is_metric = units.lower().startswith("m")

    axis_names = ["X", "Y", "Z", "A", "B", "C"]

    # Per-axis settings
    axes = []
    for i in range(num_joints):
        name = axis_names[i]
        print(f"\n--- {name} Axis ---")
        scale = ask_float(f"  Steps per {'mm' if is_metric else 'inch'}", 200.0)
        max_vel = ask_float(f"  Max velocity ({'mm' if is_metric else 'inch'}/sec)", 50.0)
        max_accel = ask_float(f"  Max acceleration ({'mm' if is_metric else 'inch'}/sec^2)", 500.0)
        min_limit = ask_float(f"  Min travel ({'mm' if is_metric else 'inch'})", -500.0 if i < 3 else -99999.0)
        max_limit = ask_float(f"  Max travel ({'mm' if is_metric else 'inch'})", 500.0 if i < 3 else 99999.0)
        axes.append({
            "name": name,
            "scale": scale,
            "max_vel": max_vel,
            "max_accel": max_accel,
            "min_limit": min_limit,
            "max_limit": max_limit,
        })

    # Create output directory
    config_dir = os.path.join(os.getcwd(), "wifi_cnc_config")
    os.makedirs(config_dir, exist_ok=True)

    # Generate INI file
    ini_path = os.path.join(config_dir, "wifi_cnc.ini")
    with open(ini_path, "w") as f:
        f.write(f"""# WiFi CNC Controller - LinuxCNC Configuration
# Generated by wifi_cnc_setup.py
# Machine: {machine_name}

[EMC]
MACHINE = {machine_name}
VERSION = 1.1

[DISPLAY]
DISPLAY = axis
CYCLE_TIME = 0.100
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = ACTUAL
MAX_FEED_OVERRIDE = 1.5
MAX_SPINDLE_OVERRIDE = 1.2
MIN_SPINDLE_OVERRIDE = 0.5
DEFAULT_LINEAR_VELOCITY = {axes[0]['max_vel'] * 0.25:.1f}
MAX_LINEAR_VELOCITY = {axes[0]['max_vel']:.1f}
EDITOR = gedit

[FILTER]
PROGRAM_EXTENSION = .py Python Script
py = python3

[RS274NGC]
PARAMETER_FILE = linuxcnc.var

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
BASE_PERIOD = 0
SERVO_PERIOD = 1000000

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[HAL]
HALFILE = wifi_cnc.hal
POSTGUI_HALFILE = postgui.hal

[HALUI]

[EMCIO]
EMCIO = io
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

[KINS]
KINEMATICS = trivkins coordinates={''.join(a['name'] for a in axes)}
JOINTS = {num_joints}

[TRAJ]
COORDINATES = {' '.join(a['name'] for a in axes)}
LINEAR_UNITS = {'mm' if is_metric else 'inch'}
ANGULAR_UNITS = degree
MAX_LINEAR_VELOCITY = {max(a['max_vel'] for a in axes):.1f}
DEFAULT_LINEAR_VELOCITY = {axes[0]['max_vel'] * 0.25:.1f}
""")

        # Write per-axis and per-joint sections
        for i, ax in enumerate(axes):
            axis_type = "LINEAR" if i < 3 else "ANGULAR"
            f.write(f"""
[AXIS_{ax['name']}]
MAX_VELOCITY = {ax['max_vel']:.1f}
MAX_ACCELERATION = {ax['max_accel']:.1f}
MIN_LIMIT = {ax['min_limit']:.1f}
MAX_LIMIT = {ax['max_limit']:.1f}

[JOINT_{i}]
TYPE = {axis_type}
HOME = 0.0
MIN_LIMIT = {ax['min_limit']:.1f}
MAX_LIMIT = {ax['max_limit']:.1f}
MAX_VELOCITY = {ax['max_vel']:.1f}
MAX_ACCELERATION = {ax['max_accel']:.1f}
SCALE = {ax['scale']:.1f}
STEPGEN_MAXACCEL = {ax['max_accel'] * 1.25:.1f}
FERROR = 5.0
MIN_FERROR = 1.0
HOME_OFFSET = 0.0
HOME_SEARCH_VEL = 0.0
HOME_LATCH_VEL = 0.0
HOME_SEQUENCE = 0
""")

    # Generate HAL file
    hal_path = os.path.join(config_dir, "wifi_cnc.hal")
    with open(hal_path, "w") as f:
        f.write(f"""# WiFi CNC Controller - HAL Configuration
# Generated by wifi_cnc_setup.py

# Load the motion controller
loadrt [KINS]KINEMATICS
loadrt motmod servo_period_nsec=[EMCMOT]SERVO_PERIOD num_joints=[KINS]JOINTS

# Load the WiFi CNC userspace component
loadusr -W wifi_cnc --ip={esp_ip} --joints={num_joints}

# Add motion controller functions to servo thread
addf motion-command-handler servo-thread
addf motion-controller servo-thread
""")

        # Per-joint connections
        for i, ax in enumerate(axes):
            f.write(f"""
# --- Joint {i} ({ax['name']} Axis) ---
setp wifi-cnc.joint.{i}.scale    [JOINT_{i}]SCALE
setp wifi-cnc.joint.{i}.maxvel   [JOINT_{i}]MAX_VELOCITY
setp wifi-cnc.joint.{i}.maxaccel [JOINT_{i}]STEPGEN_MAXACCEL

net j{i}pos-cmd  joint.{i}.motor-pos-cmd  => wifi-cnc.joint.{i}.pos-cmd
net j{i}pos-fb   wifi-cnc.joint.{i}.pos-fb   => joint.{i}.motor-pos-fb
net j{i}enable   joint.{i}.amp-enable-out    => wifi-cnc.joint.{i}.enable
net j{i}neg-lim  wifi-cnc.joint.{i}.neg-lim  => joint.{i}.neg-lim-sw-in
net j{i}pos-lim  wifi-cnc.joint.{i}.pos-lim  => joint.{i}.pos-lim-sw-in
net j{i}home-sw  wifi-cnc.joint.{i}.home-sw  => joint.{i}.home-sw-in
""")

        # E-stop chain and probe
        f.write("""
# --- E-Stop Chain ---
net estop-loop iocontrol.0.user-enable-out => iocontrol.0.emc-enable-in
net estop-out  iocontrol.0.user-enable-out => wifi-cnc.enable

# --- Probe ---
net probe-in   wifi-cnc.probe              => motion.probe-input

# --- Tool change (loopback for now) ---
net tool-change      iocontrol.0.tool-change      => iocontrol.0.tool-changed
net tool-prep-loop   iocontrol.0.tool-prepare      => iocontrol.0.tool-prepared
""")

    # Generate postgui HAL file (empty placeholder)
    postgui_path = os.path.join(config_dir, "postgui.hal")
    with open(postgui_path, "w") as f:
        f.write("# Post-GUI HAL commands (add custom connections here)\n")

    # Generate empty tool table
    tool_path = os.path.join(config_dir, "tool.tbl")
    with open(tool_path, "w") as f:
        f.write("T1 P1 Z0.000 D0.125 ;Default tool\n")

    print(f"\n{'=' * 50}")
    print(f"  Configuration generated in: {config_dir}/")
    print(f"{'=' * 50}")
    print(f"\nFiles created:")
    print(f"  wifi_cnc.ini   - Main config")
    print(f"  wifi_cnc.hal   - HAL connections")
    print(f"  postgui.hal    - Post-GUI HAL (empty)")
    print(f"  tool.tbl       - Tool table")
    print(f"\nTo use:")
    print(f"  1. Install the HAL component:")
    print(f"     sudo halcompile --install --userspace wifi_cnc.c")
    print(f"  2. Copy config folder to ~/linuxcnc/configs/")
    print(f"     cp -r wifi_cnc_config ~/linuxcnc/configs/")
    print(f"  3. Launch LinuxCNC:")
    print(f"     linuxcnc ~/linuxcnc/configs/wifi_cnc_config/wifi_cnc.ini")

if __name__ == "__main__":
    main()
